version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running unit tests in pytest and generating test reports
      - pytest --junitxml=./pytest-reports/unit-test-reports.xml
reports:
  PytestReports:
    files:
        -'**/*'
    base-directory: target/pytest-reports

