version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    - echo Running unit tests in pytest
    - pytest --junitxml=./pytest-reports/unit-test-reports.xml
  reports:
    PytestReports:
      files:
        -'**/*'
      base-directory: target/pytest-reports

